name: appcar
description: AppCar - Flutter client for vehicle booking
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  flutter_secure_storage: ^7.0.1
  web_socket_channel: ^2.2.0
  intl: ^0.18.0
  connectivity_plus: ^4.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
